### ISSUE TITLE
dsem blocking submission of TMB 1.9.11

### ISSUE THREAD

**Issue by kaskr** [James-Thorson-NOAA/dsem#19]
TMB no longer writes a file `Matrix-version` on installation. The check here:

https://github.com/James-Thorson-NOAA/dsem/blob/ffad27d69249926b4771fc804d1adab9ae9fd65e/R/zzz.R#L7

assumes the existence of the file, and then fails!

Solution: Don't do that check :) TMB already does it for you when the TMB namespace is attached (which happens when you do `library(dsem)`).

**Comment by James-Thorson-NOAA** [comment]
Thanks for the update!  Are you saying I should immediately submit an updated version of phylosem and dsem to CRAN that excludes this line, or can I simply do that change the next time I submit an updated version to CRAN?

**Comment by kaskr** [comment]
Yeah, if you could submit to CRAN soon it would be great - thanks :)

**Comment by James-Thorson-NOAA** [comment]
OK, just to see if I understood correctly ... do you mind checking the [dev branch](https://github.com/James-Thorson-NOAA/dsem/tree/dev) to see if that fixes things?  

If I don't hear back by COB today and I'll go ahead and submit tonight.

**Comment by kaskr** [comment]
Yes, that looks good. I think you're right about removing `checkDepPackageVersion` entirely.

**Comment by James-Thorson-NOAA** [comment]
OK, I just uploaded the updates to `sem` and `phylosem` to CRAN.  I assume those should be accepted and updated in CRAN in 1-2 days.  I'll post updates here if there's some hitch.

**Comment by kaskr** [comment]
Jim, thanks for fixing this quickly!
