### ISSUE TITLE
R^2 or DE values?

### ISSUE THREAD

**Issue by RayCzajaJr** [James-Thorson-NOAA/dsem#24]
Currently, I am unaware of any function or output, within the package, that gives R^2 or deviance explained values. While calculating these values is not too difficult, automatic output, or within package functions, would be helpful.

**Comment by James-Thorson-NOAA** [comment]
Thanks for posting!  I've been pondering a bit.  It would be easy to calculate conditional percent-deviance-explained (CPDE).  However, dsem allows you to turn off measurement errors, in which case the CPDE is undefined.  Thinking out loud here ... I could have a switch where it only calculates  CPDE if family!="fixed" for any variable.

What is the `family` argument in your case?

**Comment by RayCzajaJr** [comment]
Gaussian (although I did log transform my data). Sorry for the short reply,
I’m out of office today but wanted to respond to this email.

**Comment by James-Thorson-NOAA** [comment]
If you send me a minimal example via email, I could test my assumption about how easiest to do this.  So that minimal example would be:
1. an RDS containing tsdata
2. an R script containing 5-10 lines of code total, which loads the RDS and runs the model

You interested in that path?

**Comment by RayCzajaJr** [comment]
If you refer to our email chain with arnaud from last week, would that
include what you need?

**Comment by James-Thorson-NOAA** [comment]
From the example provided, it appears you're using `family = "fixed"`.  I don't have a proposal for calculating R2 in that instance.
