### ISSUE TITLE
plots

### ISSUE THREAD

**Issue by JaneSullivan-NOAA** [James-Thorson-NOAA/dsem#25]
Hi Jim,
I'd like to get your thoughts on modifying the dsem plots as follows:
Instead of having separate link strength and p-value plots, what about using * on the link strength plot to denote significance levels (e.g., *<=0.05, **<=0.01, or some version of that). 

In other words, this plot:
![image](https://github.com/user-attachments/assets/72dc3352-ce9a-4ed5-94ea-9ef993c3a93a)

Would look like this instead:
![image](https://github.com/user-attachments/assets/12a77670-c067-4987-be4d-60e64701a248)

**Comment by James-Thorson-NOAA** [comment]
yeah, I'm happy with that :)  I also sometimes put p-values or standard errors in paranetheses (e.g., Fig-2 [here](https://arxiv.org/pdf/2401.10193)).  I'd say that another big need is to make an automated plot that usefully shows both simultaneous and lagged effects in a single diagram.  I'd definitely welcome code suggestions, ideally via a PR off the dev branch

**Comment by ScottLarge-NOAA** [comment]
Just want to add a +1 to the p-value and/or standard errors plots... I'm not sure how I can help, though! @James-Thorson-NOAA , if you have a suggested path forward, let me know!

**Comment by James-Thorson-NOAA** [comment]
@JaneSullivan-NOAA and @ScottLarge-NOAA thanks for weighing in!

Would you want this on the `plot(out)` style plots like you get in the `?dsem` reference example?

![image](https://github.com/user-attachments/assets/e6a7b39f-488a-4444-aed2-69f0f3329320)

I'm pushing to the dsem@dev branch some options doing this using the `igraph` plots (see below).  However, the automated `ggraph` style plots are still a work in progress.  

![image](https://github.com/user-attachments/assets/d131b728-50fc-44ab-abc8-296a7316d492)

**Comment by James-Thorson-NOAA** [comment]
OK, on the dev branch I now have the `ggraph` style plot set up, e.g., using:
```R
plot( fit, edge_label = "value_and_stars", style="ggraph")
```
I'm closing for now, but feel free to keep discussing here.  

![image](https://github.com/user-attachments/assets/ca6113f8-fc1e-43c7-ac0e-3d215827f0d5)
