### ISSUE TITLE
DHARMa residuals

### ISSUE THREAD

**Issue by agruss2** [James-Thorson-NOAA/dsem#27]
@James-Thorson-NOAA (cc: @RayCzajaJr)
Hello, 
As we discussed, it would be a good idea to compute and plot DHARMa residuals to have a means (among others) to evaluate a DSEM.
Today, I have explored ways to do that and it was a bit less straightforward to do that compared to doing it for a VAST model for example. 
Anyway, I am going to copy/paste below some of the code I have produced today, to get some feedback and determine whether what I did makes sense, and also because this may interest other dsem others. Below, the code intends to generate simulated data and then to compute and plot DHARMa residuals for one of the variables of the DSEM, namely small blue crab log-catch rate.

```R
######## Evaluate the DSEM using DHARMa residuals
#### Simulate new data 
y_ir_ts <- simulate ( fit,
	nsim = 100,
	resimulate_gmrf = TRUE )
y_ir <- array( NA, dim = c( nrow( y_ir_ts[[1]] ), ncol( y_ir_ts[[1]] ), 100 ), dimnames = NULL )
for ( i in 1 : 100 ) { y_ir[,,i] <- unlist( y_ir_ts[[i]] ) }

#### Generate DHARMa residuals for small blue crab and plot the histogram and QQ-plot of these DHARMa residuals
variable <- "BlueCrabSmall"

## Generate DHARMa residuals
dharmaRes <- DHARMa::createDHARMa( simulatedResponse = y_ir[,1,,drop = T], 
	observedResponse = GalvestonBay_GN_YearMean_log$BlueCrabSmall, 
	fittedPredictedResponse = fit$obj$report()$y_tj[,1] )

## Produce and save an histogram of DHARMa residuals 
val <- dharmaRes$scaledResiduals
val[val == 0] <- -0.01
val[val == 1] <- 1.01
jpeg( make.filename( paste0( "Histogram_of_DHARMa_residuals_", variable, ".png" ), FiguresDir ), 
	width = 6, height = 7, units = "in", res = 600 )
		hist( val, breaks = seq( -0.02, 1.02, len = 23 ), col = c( "red", rep( "lightgrey", 20 ), "red" ),
			main = "", xlab = "Residuals", cex.main = 2.5 )
dev.off()

## Produce and save a QQ-plot of DHARMa residuals 
jpeg( make.filename( paste0( "QQplot_of_DHARMa_residuals_", variable, ".png" ), FiguresDir ), 
	width = 6, height = 7, units = "in", res = 600 )
		gap::qqunif( dharmaRes$scaledResiduals, pch = 2, bty = "n", logscale = F, col = "black", cex = 0.6,
			main = "", cex.main = 2.5 )
dev.off()
```

Many thanks and talk soon.
Cheers,
Arnaud

**Comment by James-Thorson-NOAA** [comment]
@agruss2 Thanks for suggesting an option, and also for prompting some continued attention :)

However, `simulate( ..., resimulate_gmrf = TRUE)` will not condition upon the empirical Bayes estimates or inform the predicted value of random effects, so it will not give useful residuals.

However, I have just added a new function `loo_residuals` which I think should work for any combination of families (i.e. a mix of family = "fixed" and measurement-error options).   See e.g. code here:

```R
devtools::install_github( "James-Thorson-NOAA/dsem@dev", force=TRUE )
library(dsem)

x = rnorm(100)
y = 1 + 0.5 * x + rnorm(100)
x[sample(seq_along(x),size=10,replace=FALSE)] = NA
y[sample(seq_along(x),size=10,replace=FALSE)] = NA
tsdata = ts(data.frame( x=x, y=y ))

fit = dsem( tsdata = tsdata,
            sem = "x -> y, 0, slope" )
resid = loo_residuals(fit)
hist(resid)
```

Could either/both of you take a look and do some road-testing? 

I'll close for now, but happy to reopen and/or continue discussing here.

**Comment by agruss2** [comment]
Hi Jim, 
Thank you so much for looking at it and working on a solution, this is exciting and much appreciated.
Tomorrow I will try and take a look and do some road-testing and will keep you guys posted.
Have both a nice week and chat soon!

**Comment by agruss2** [comment]
@James-Thorson-NOAA (cc: @RayCzajaJr)
Thanks a lot once again for the "loo_residuals" function. I have first explored it and then I was willing to apply it using Ray's data. However, when running ```fittedPredictedResponse <- loo_residuals( fit, what = "loo" )```,  I am getting the following error message:
```R
Error in `[<-.default`(`*tmp*`, df[r, 1], df[r, 2], value = NA) : 
  subscript out of bounds
```
I reckon that providing only this error message to you Jim will not be of much help and that we should provide you with a minimal example?

**Comment by James-Thorson-NOAA** [comment]
I was able to replicate the problem in the wolf-moose example in the vignettes, and fixed it in that instance.  are you willing to check with the other data set again?

**Comment by agruss2** [comment]
Thank you very much, Jim! Success now :)
I am going to come back here soon with the code for small crab for generating the residuals and then plotting them - talk again very soon!

**Comment by agruss2** [comment]
@James-Thorson-NOAA (cc: @RayCzajaJr)
So here is the updated version of the code to generate and plot residuals for small blue crab:
```R
######## Evaluate the DSEM using DHARMa residuals
#### Generate leave-one-out residuals
samples <- loo_residuals( fit, what = "samples" )
fittedPredictedResponse <- loo_residuals( fit, what = "loo" )

#### Generate DHARMa residuals 
which_use <- which( !is.na( data_GB ) )
dharmaRes <- DHARMa::createDHARMa( simulatedResponse = apply( samples, MARGIN = 3, FUN = as.vector )[which_use,],
	observedResponse = as.vector( data_GB )[which_use],
	fittedPredictedResponse = fittedPredictedResponse$est )

#### Plot the histogram and QQ-plot of DHARMa residuals for small blue crab
variable <- colnames( data_GB )[1] 

## Produce and save an histogram of DHARMa residuals 
val <- dharmaRes$scaledResiduals
val[val == 0] <- -0.01
val[val == 1] <- 1.01
val <- val[variable_name == variable]
jpeg( make.filename( paste0( "Histogram_of_DHARMa_residuals_", variable, ".png" ), FiguresDir ), 
	width = 6, height = 7, units = "in", res = 600 )
		hist( val, breaks = seq( -0.02, 1.02, len = 23 ), col = c( "red", rep( "lightgrey", 20 ), "red" ),
			main = "", xlab = "Residuals", cex.main = 2.5 )
dev.off()

## Produce and save a QQ-plot of DHARMa residuals 
jpeg( make.filename( paste0( "QQplot_of_DHARMa_residuals_", variable, ".png" ), FiguresDir ), 
	width = 6, height = 7, units = "in", res = 600 )
		gap::qqunif( dharmaRes$scaledResiduals[variable_name == variable], 
			pch = 2, bty = "n", logscale = F, col = "black", cex = 0.6, main = "", cex.main = 2.5 )
dev.off()
```
Closing this issue now, and many thanks once again, Jim :)
